INSERT INTO categories (name, icon, color, is_income) VALUES
('Salary', 'briefcase', '#4CAF50', true),
('Freelance', 'laptop', '#66BB6A', true),
('Interest', 'percent', '#81C784', true),
('Refunds', 'refresh', '#A5D6A7', true),
('Gifts Received', 'gift', '#C8E6C9', true),
('Other Income', 'plus-circle', '#E8F5E9', true),
('Food & Dining', 'utensils', '#FF5722', false),
('Groceries', 'shopping-cart', '#FF7043', false),
('Transport', 'car', '#FF9800', false),
('Rent', 'home', '#FFA726', false),
('Utilities', 'zap', '#FFB74D', false),
('Shopping', 'shopping-bag', '#E91E63', false),
('Entertainment', 'film', '#9C27B0', false),
('Health', 'heart', '#F44336', false),
('Education', 'book', '#3F51B5', false),
('Subscriptions', 'repeat', '#673AB7', false),
('Personal Care', 'user', '#795548', false),
('Travel', 'map-pin', '#00BCD4', false),
('Gifts & Donations', 'gift', '#FF4081', false),
('EMI', 'credit-card', '#F57C00', false),
('Insurance', 'shield', '#0288D1', false),
('Miscellaneous', 'more-horizontal', '#9E9E9E', false);
